#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy |& /usr/bin/logshifter -tag diy &
export JAVA_HOME=/etc/alternatives/java_sdk_1.8.0
export PATH=$JAVA_HOME/bin:$PATH

export BOOT_LOCAL_REPO=$OPENSHIFT_DATA_DIR/boot_repository
export BOOT_HOME=$OPENSHIFT_DATA_DIR/boot


$OPENSHIFT_REPO_DIR/diy/boot.sh build-cljs -- start-server |& /usr/bin/logshifter -tag diy &
